name: Create Archive
on:
  push:
    tags: [ 'v*.*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
        rm -rf .git
        rm -rf .github
        git config --global user.email "noone@chemeketa.edu"
        git config --global user.name "ChemeketaCS"
        git init
        git add -A
        git commit -m "Initial template project"
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'TemplateComboProject.zip'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "TemplateComboProject.zip"
        tag: ${{ github.ref_name }}
        token: ${{ secrets.GITHUB_TOKEN }}
